db.driver=org.postgresql.Driver
db.url=${GYMCRM_PROD_DB_URL}
db.username=${GYMCRM_PROD_DB_USERNAME}
db.password=${GYMCRM_PROD_DB_PASSWORD}

hibernate.hbm2ddl.auto=validate
hibernate.show_sql=false
hibernate.format_sql=false

management.endpoint.health.show-details=never
