db.driver=org.h2.Driver
db.url=jdbc:h2:mem:gymcrm;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
db.username=sa
db.password=

spring.profiles.default=local

hibernate.hbm2ddl.auto=create-drop
hibernate.show_sql=false
hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.metrics.tags.application=gym-crm
