db.driver=org.postgresql.Driver
db.url=${GYMCRM_STG_DB_URL}
db.username=${GYMCRM_STG_DB_USERNAME}
db.password=${GYMCRM_STG_DB_PASSWORD}

hibernate.hbm2ddl.auto=validate
hibernate.show_sql=false
hibernate.format_sql=true
